#apiVersion: apps/v1
#kind: Deployment
#metadata:
 # name: Deployment
 # labels:
 #   app: kubernetes # dockerhub
#spec:
 # replicas: 5
 # selector:
  #  matchLabels:
   #   app: kubernetes
  #template:
  #  metadata:
   #   labels:
    #    app: kubernetes
   # spec:
    #  containers:
     # - name: kubernetes
      #  image: 202106601/kubernetes
       # ports:
       # - containerPort: 8000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
spec:
  selector:
    labels:
      app: kubernetes
  replicas: 5
  template:
    metadata:
      #name: kubernetes-deployment
      labels:
        #name: kubernetes-deployment
        name: kubernetes
        app: kubernetes
    spec:
      containers:
        - name: kubernetes
          image: 202106601/kubernetes
          #imagePullPolicy: Never
          env:
            - name: Web_Port
              value: "8000"
            - name: Pod_Ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP

  