apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  labels:
    app: Kubernetes # dockerhub
spec:
  replicas: 5
  selector:
    matchLabels:
      app: Kubernetes
  template:
    metadata:
      labels:
        app: Kubernetes
    spec:
      containers:
      - name: Kubernetes
        image: 202106601/Kubernetes
        ports:
        - containerPort: 8000