
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  selector:
    matchLabels:
      app: kubernetes
  replicas: 5
  template:
    metadata:
      name: kubernetes
      labels:
        name: kubernetes
        app: kubernetes
    spec:
      containers:
        - name: kubernetes
          image: 202106601/kubernetes
          #imagePullPolicy: Never
          env:
            - name: Web_Port
              value: "8000"
            - name: Pod_Ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP

  