apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  labels:
    app: kuber # dockerhub
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      containers:
      - name: kuber
        image: 202106601/kuber
        ports:
        - containerPort: 8000