apiVersion: v1
kind: Service
metadata:
  name: bully-service
spec:
  #clusterIP: None
  type: NodePort
  selector: 
    app: kubernetes
  ports: 
    - protocol: TCP
      port: 8000
      targetPort: 8000