apiVersion: v1
kind: Service # Type of Kubernetes resource, which is Service
metadata:
  name: bully-service
spec:
  clusterIP: None
  #type: NodePort
  selector: # specifies the set of pods targeted by the service. 
    app: kubernetes
  ports: 
    - protocol: TCP
      port: 8000
      targetPort: 8000